# Generated by Django 6.0.6 on 2026-06-13 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(help_text='Debe ser único en la empresa.', max_length=254, unique=True, verbose_name='Email')),
                ('puesto', models.CharField(db_index=True, max_length=100, verbose_name='Puesto')),
                ('salario', models.DecimalField(decimal_places=2, help_text='Monto en la moneda de la empresa. No puede ser negativo.', max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='El salario no puede ser negativo.')], verbose_name='Salario')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
